source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GVCustomView_Example', :exclusive => true do
  pod "GVCustomView", :path => "../"
end

target 'GVCustomView_Tests', :exclusive => true do
  pod "GVCustomView", :path => "../"

  
end
